Repository softeerbootcamp4th/data_engineering_course_materials, pull requests merged in 2024-07, with the labels that each got.

#55 [DE한경훈] Feat: 한경훈 W1M1 submit
  missions/W1/W1M1.ipynb
Labels: W1M1

#42 DE윤준혁: W1M1
  missions/W1/mtcars/mtcars.ipynb
Labels: W1M1

#36 W1M1 - mtcars 데이터셋 분석하기
  missions/W1/EDA_mtcars.ipynb
Labels: W1M1

#22 feat(missions/W1/M1): pandas practice using mtcars
  missions/W1/M1/mtcars.csv
  missions/W1/M1/mtcars.ipynb
Labels: W1M1

#31 W1M2 SQL 미션 제출
  .gitignore
  missions/W1/README.md
  missions/W1/assets/figure-1.png
  missions/W1/assets/figure-2.png
  missions/W1/assets/figure-3.png
  missions/W1/assets/figure-4.png
  missions/W1/assets/figure-5.png
  missions/W1/sql/chinook.db
  missions/W1/sql/sql.ipynb
Labels: W1M2

#37 W1M2 - SQL Tutorial
  missions/W1/sql_tutorial.ipynb
Labels: W1M2

#21 DE이민섭 W1M2
  .gitignore
  missions/W1/chinook.db
  missions/W1/sql_tutorial.ipynb
Labels: W1M2

#18 [DE이구] feat: add mission2.ipynb
  missions/W1/mission2.ipynb
Labels: W1M2

#44 DE윤준혁: W1M3 - ETL
  missions/W1/ETL/.gitignore
  missions/W1/ETL/etl_project_gdp.py
  missions/W1/ETL/etl_project_gdp_with_sql.py
Labels: W1M3

#23 DE이민섭 W1M3
  .gitignore
  missions/W1/Countries_by_GDP.json
  missions/W1/countries_by_region.csv
  missions/W1/etl_project_gdp.py
  missions/W1/etl_project_gdp_with_sql.py
Labels: W1M3

#43 DE윤준혁: W1M2
  missions/W1/sql/.gitignore
  missions/W1/sql/chinook.db
  missions/W1/sql/sql.ipynb
Labels: W1M2

#24 feat(missions/W1/M2): sql practice
  missions/W1/M2/csv/categories.csv
  missions/W1/M2/csv/customers.csv
  missions/W1/M2/csv/employees.csv
  missions/W1/M2/csv/orderDetails.csv
  missions/W1/M2/csv/orders.csv
  missions/W1/M2/csv/products.csv
  missions/W1/M2/csv/shippers.csv
  missions/W1/M2/csv/suppliers.csv
  missions/W1/M2/sql.ipynb
Labels: W1M2

#17 [DE이구] feat: add mission1.ipynb
  missions/W1/mission1.ipynb
Labels: W1M1

#45 DE윤준혁: W2M1 - Pool
  missions/W2/multiprocessing_pool.py
Labels: W2M1

#26 feat(missions/W2/M1): multiprocessing.Pool practice
  missions/W2/M1/M1.py
Labels: W2M1

#50 [DE이구] feat: add mission1.py
  missions/W1/etl_project_gdp.py
  missions/W1/etl_project_gdp_with_sql.py
  missions/W1/get_region_info.py
  missions/W1/mission1.ipynb
  missions/W1/mission2.ipynb
  missions/W2/mission1.py
Labels: W2M1

#61 W2H1 - Multiprocessing: Pool
  missions/W2/multiprocessing_with_pool.py
Labels: W2M1

#25 feat(missions/W1/M3): ETL process practice using wikipedia
  missions/W1/M3/config.yaml
  missions/W1/M3/country_region.json
  missions/W1/M3/country_region_extractor.py
  missions/W1/M3/etl_project_gdp.py
  missions/W1/M3/etl_project_gdp_with_sql.py
Labels: W1M3

#73 DE이용선 - W1M1
  missions/W1/W1M1.ipynb
Labels: W1M1

#70 DE홍주원_W1M1
  .gitignore
  missions/W1/W1M1/mtcars.csv
  missions/W1/W1M1/mtcars.ipynb
Labels: W1M1

#127 DE이용선 - W2M4
  missions/W2/W2M4 - Multiprocessing: all-in-one.py
Labels: W2M4

#132 W2M4 - Multiprocessing: all-in-one
  missions/W2/Mission4.py
Labels: W2M4

#78 DE홍주원_W2M4
  .gitignore
  missions/W2/W2M4/multoprocessing_all_in_one.py
Labels: W2M4

#90 DE김영일_W2M4
  missions/W1/README.md
  missions/W1/w1m2_sql.ipynb
  missions/W1/w1m2_sqltut.xlsx
  missions/W1/w1m3_etl_project_gdp.py
  missions/W1/w1m3_etl_project_gdp_with_sql.py
  missions/W1/w1m3_extract_region_data_with_mppool.py
  missions/W2/w2m1_pool.py
  missions/W2/w2m2_process.py
  missions/W2/w2m3_thread_queue.py
  missions/W2/w2m4_thread_all.py
Labels: W2M4

#112 W2M5 - Sentiment Analysis
  missions/W2/rankingdakcom_webcrawling.py
  missions/W2/word_cloud_rankingdakcom.ipynb
  missions/W2/word_cloud_sentiment140.ipynb
  missions/W2/word_cloud_sentiment140_with_text.ipynb
Labels: W2M5

#82 DE김영일_W1M2
  missions/W1/w1m2_sql.ipynb
  missions/W1/w1m2_sqltut.xlsx
Labels: W1M2

#77 DE이용선 - W1M2
  missions/W1/W1M2 - SQL Tutorial.ipynb
Labels: W1M2

#106 [DE한경훈] Feat: 한경훈 W1M2 submit
  missions/W1/W1M2.ipynb
Labels: W1M2

#143 DE박상민_W2m4
  missions/w2m4.py
Labels: W2M4

#150 [DE한경훈] Feat: 한경훈 W2M5 (ipynb, py, json, yaml) files submit
  missions/W1/Update_country_region.py
  missions/W1/W1M2.ipynb
  missions/W1/continent_countries.json
  missions/W1/etl_project_gdp_with_sql.py
  missions/W1/path_url_settings.yaml
  missions/W2/W2M5.ipynb
  missions/W2/W2M5_car_extract_setting.json
  missions/W2/W2M5_setting.yaml
  missions/W2/W2M5_youtube_extract.py
  missions/W2/W2M5_youtube_transform_load.py
Labels: W2M5

#94 DE장철희: W2M4-multiprocessing all-in-one
  .gitignore
  missions/W1/README.md
  missions/W1/assets/figure-1.png
  missions/W1/assets/figure-2.png
  missions/W1/assets/figure-3.png
  missions/W1/assets/figure-4.png
  missions/W1/assets/figure-5.png
  missions/W1/mtcars.csv
  missions/W2/all.py
Labels: W2M4

#160 W3M1: Hadoop Single Node Cluster on Docker
  missions/W3/Single-Node-Cluster/Dockerfile
  missions/W3/Single-Node-Cluster/core-site.xml
  missions/W3/Single-Node-Cluster/docker-compose.yaml
  missions/W3/Single-Node-Cluster/hdfs-site.xml
  missions/W3/Single-Node-Cluster/mapred-site.xml
  missions/W3/Single-Node-Cluster/readme.md
  missions/W3/Single-Node-Cluster/samplefile.txt
  missions/W3/Single-Node-Cluster/start-hadoop.sh
  missions/W3/Single-Node-Cluster/yarn-site.xml
Labels: W3M1

#167 W3M1 - Hadoop Single-Node Cluster on Docker
  missions/W3/Single-Node/Dockerfile
  missions/W3/Single-Node/README.MD
  missions/W3/Single-Node/etc/hadoop/core-site.xml
  missions/W3/Single-Node/etc/hadoop/hdfs-site.xml
  missions/W3/Single-Node/etc/hadoop/mapred-site.xml
  missions/W3/Single-Node/etc/hadoop/yarn-site.xml
  missions/W3/Single-Node/img/browse_directory_1.png
  missions/W3/Single-Node/img/browse_directory_2.png
  missions/W3/Single-Node/img/browse_directory_3.png
  missions/W3/Single-Node/img/browse_directory_4.png
  missions/W3/Single-Node/img/browse_directory_5.png
  missions/W3/Single-Node/img/create_directory_1.png
  missions/W3/Single-Node/img/create_directory_2.png
  missions/W3/Single-Node/img/create_directory_3.png
  missions/W3/Single-Node/img/upload_file_1.png
  missions/W3/Single-Node/img/upload_file_2.png
  missions/W3/Single-Node/img/upload_file_3.png
  missions/W3/Single-Node/run.sh
  missions/W3/Single-Node/scripts/initialize.sh
  missions/W3/Single-Node/scripts/start.sh
Labels: W3M1

#166 DE최우형_W3M1
  .gitignore
  missions/W2/M1_4/W2M1 - Multiprocessing: Pool.ipynb
  missions/W3/M1/Dockerfile
  missions/W3/M1/README.md
  missions/W3/M1/core-site.xml
  missions/W3/M1/entrypoint.sh
  missions/W3/M1/hdfs-site.xml
  missions/W3/M1/mapred-site.xml
  missions/W3/M1/yarn-site.xml
  missions/W3/M2/README.md
  missions/W3/M3/README.md
  missions/W3/M4/README.md
  missions/W3/M5/README.md
  missions/W3/M6/README.md
Labels: W3M1

#163 DE김영일_W3M1
  missions/W1/README.md
  missions/W1/w1m2_sql.ipynb
  missions/W1/w1m2_sqltut.xlsx
  missions/W1/w1m3_etl_project_gdp.py
  missions/W1/w1m3_etl_project_gdp_with_sql.py
  missions/W1/w1m3_extract_region_data_with_mppool.py
  missions/W2/w2m1_pool.py
  missions/W2/w2m2_process.py
  missions/W2/w2m3_thread_queue.py
  missions/W2/w2m4_thread_all.py
  missions/W2/w2m5_sentiment_analysis.ipynb
  missions/W2/w2m5_team_analysis_etl.ipynb
  missions/W2/w2m5_team_analysis_prototype.py
  missions/W3/submission1_single_node_cluster_hadoop/Dockerfile
  missions/W3/submission1_single_node_cluster_hadoop/Makefile
  missions/W3/submission1_single_node_cluster_hadoop/README.md
  missions/W3/submission1_single_node_cluster_hadoop/core-site.xml
  missions/W3/submission1_single_node_cluster_hadoop/docker-compose.yml
  missions/W3/submission1_single_node_cluster_hadoop/format-hdfs.sh
  missions/W3/submission1_single_node_cluster_hadoop/hdfs-site.xml
  missions/W3/submission1_single_node_cluster_hadoop/mapred-site.xml
  missions/W3/submission1_single_node_cluster_hadoop/yarn-site.xml
Labels: W3M1

#162 DE윤준혁: W3M1 - Hadoop Single Node Cluster on Docker
  missions/W3/Single-Node-Cluster/Dockerfile
  missions/W3/Single-Node-Cluster/core-site.xml
  missions/W3/Single-Node-Cluster/docker-compose.yaml
  missions/W3/Single-Node-Cluster/hdfs-site.xml
  missions/W3/Single-Node-Cluster/mapred-site.xml
  missions/W3/Single-Node-Cluster/readme.md
  missions/W3/Single-Node-Cluster/samplefile.txt
  missions/W3/Single-Node-Cluster/start-hadoop.sh
  missions/W3/Single-Node-Cluster/yarn-site.xml
Labels: W3M1

#232 feat(missions/W4/M2): W4M2 - NYC TLC Trip Record Analysis using Apache Spark
  .gitignore
  missions/W1/mtcars.csv
  missions/W4/M2/.gitignore
  missions/W4/M2/README.md
  missions/W4/M2/docker-compose.yaml
  missions/W4/M2/hourly_trips.png
  missions/W4/M2/yello_taxi.ipynb
  missions/W4/M2/yello_taxi_job.sh
Labels: W4M2
